---
- name: Install nginx
  hosts: web
  become: true

  tasks:

    - name: Install depends 
      ansible.builtin.apt:
        name: 
          - nginx
          - curl
          - gnupg2
          - ca-certificates
        update_cache: yes

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb http://nginx.org/packages/ubuntu  jammy nginx"
        state: present

    - name: Install nginx
      ansible.builtin.apt:
        name: 
          - nginx
        update_cache: yes

    - name: Copy config nginx
      ansible.builtin.copy:
        src: ./files/nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: '0744'

    - name: Create a directory for cache
      ansible.builtin.file:
        path: /var/nginx/cache
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
