---
- name: Install nginx
  hosts: web
  become: true

  tasks:

    - name: Install depends 
      ansible.builtin.apt:
        name: 
          - curl
          - gnupg2
          - ca-certificates
        update_cache: yes

    - name: Add nginx GPG apt Key
      ansible.builtin.apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present

    - name: Add nginx repository
      apt_repository:
        repo: "deb http://nginx.org/packages/mainline/ubuntu jammy nginx"
        state: present

    - name: Install nginx
      ansible.builtin.apt:
        name: 
          - nginx
        update_cache: yes

    - name: Copy config nginx
      ansible.builtin.copy:
        src: "./files/nginx/{{ item }}"
        dest: /etc/nginx/
        mode: '0644'
      loop:
        - nginx.conf
        - nginx-selfsigned.crt
        - nginx-selfsigned.key
        - dhparam.pem
      notify:
        - Restart nginx

    - name: Create a directory for cache
      ansible.builtin.file:
        path: /var/nginx/cache
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data
      notify:
        - Restart nginx
        - Restart exporter

    - name: Add the user nginx-exporter
      ansible.builtin.user:
        name: nginx-exporter
        create_home: false
        shell: /bin/false
        system: true

    - name: Copy exporter bin
      ansible.builtin.copy:
        src: ./files/nginx/nginx-prometheus-exporter
        dest: /usr/local/bin/
        mode: "0774"
        owner: nginx-exporter
        group: nginx-exporter
      notify:
        - Restart exporter

    - name: Copy exporter service
      ansible.builtin.copy:
        src: ./files/nginx/nginx_exporter.service
        dest: /etc/systemd/system/
      notify:
        - Restart exporter

  handlers:
    
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Restart exporter
      ansible.builtin.service:
        name: nginx_exporter
        state: restarted
        daemon_reload: true


