---
- name: Install PostgreSQL
  hosts: db
  become: true

  tasks:

    - name: Add key for PostgreSQL
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add repo PostgreSQL
      ansible.builtin.apt_repository:
        repo: "deb https://apt.postgresql.org/pub/repos/apt jammy-pgdg main"
        state: present
        filename: pgdg

    - name: Install packeges
      ansible.builtin.apt:
        name: 
          - postgresql
          - postgresql-contrib
          - pgbouncer
          - libpq-dev
          - python3-psycopg2
        update_cache: yes

    - name: Update config PostgreSQL
      ansible.builtin.template:
        src: ./files/pg_config.j2
        dest: /etc/postgresql/16/main/conf.d/bingo.conf
        mode: '0644'

    - name: Copy config pgbouncer
      ansible.builtin.copy:
        src: "./files/{{ item }}"
        dest: /etc/pgbouncer/
        mode: '0644'
      loop:
        - userlist.txt
        - pgbouncer.ini

    - name: Restart Service
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - postgresql
        - pgbouncer

    - name: Grant access remote connect
      community.postgresql.postgresql_pg_hba:
        dest: /etc/postgresql/16/main/pg_hba.conf
        contype: host
        users: bingo
        source: ::/0
        databases: bingo
        method: password
        create: true

    - name: Add user Bingo
      become_user: postgres
      community.postgresql.postgresql_user:
        name: bingo
        password: bingo

    - name: Create a new database bingo
      become_user: postgres
      community.postgresql.postgresql_db:
        name: bingo
        owner: bingo

    - name: Create a directory for bingo
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: ansible
        group: ansible
      loop:
        - /opt/bingo
        - /opt/bongo/logs/12690b3e5e

    - name: log file
      ansible.builtin.file:
        path: /opt/bongo/logs/12690b3e5e/main.log
        state: touch
        mode: '0755'
        owner: ansible
        group: ansible

    - name: Copy bingo
      ansible.builtin.copy:
        src: "./files/{{ item.file }}"
        dest: /opt/bingo/
        owner: ansible
        group: ansible
        mode: "{{ item.mode }}"
      loop:
        - file: bingo
          mode: "0744"
        - file: config.yaml
          mode: "0644"

    - name: "Bingo prepare_db"
      become_user: ansible
      ansible.builtin.shell: 
        cmd: "./bingo prepare_db"
        chdir: /opt/bingo

    - name: Create index
      become_user: postgres
      community.postgresql.postgresql_idx:
        db: bingo
        table: "{{ item }}"
        columns: id
        name: "idx_{{ item }}"
        unique: true
      loop:
        - customers
        - movies
        - sessions



